"use client";

import { useQuery } from "@tanstack/react-query";
import { ArrowRight, HandCoins } from "lucide-react";
import { AppShell } from "@/components/layout/app-shell";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { fetchSettlements } from "@/lib/api";
import { formatCurrency } from "@/lib/utils";

export default function SettlementsPage() {
  const settlementsQuery = useQuery({
    queryKey: ["settlements"],
    queryFn: fetchSettlements,
  });

  return (
    <AppShell
      title="Settlement suggestions"
      description="Review the current minimized transfer plan generated by the backend settlement engine."
    >
      {settlementsQuery.isLoading ? (
        <Card className="border-0 bg-white/84 shadow-lg">
          <CardContent className="h-48 animate-pulse" />
        </Card>
      ) : settlementsQuery.isError || !settlementsQuery.data ? (
        <Card className="border-0 bg-white/84 shadow-lg">
          <CardHeader>
            <CardTitle>Unable to load settlements</CardTitle>
            <CardDescription>
              Check that the backend is running and settlement data has been generated.
            </CardDescription>
          </CardHeader>
        </Card>
      ) : (
        <div className="space-y-6">
          <Card className="border-0 bg-white/84 shadow-lg backdrop-blur">
            <CardHeader>
              <CardTitle>Current transfer plan</CardTitle>
              <CardDescription>
                The engine minimizes the number of transactions needed to settle partner balances.
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              {settlementsQuery.data.settlements.length === 0 ? (
                <div className="rounded-3xl border border-dashed border-[#14312c]/20 bg-[#14312c]/[0.03] p-8 text-center">
                  <div className="mx-auto mb-3 flex size-14 items-center justify-center rounded-2xl bg-emerald-100 text-emerald-700">
                    <HandCoins className="size-6" />
                  </div>
                  <p className="font-medium text-[#14312c]">No transfers needed right now.</p>
                  <p className="mt-2 text-sm text-muted-foreground">
                    Partner wallets already align with the expected ownership share of profit.
                  </p>
                </div>
              ) : (
                settlementsQuery.data.settlements.map((settlement, index) => (
                  <div
                    key={`${settlement.from}-${settlement.to}-${index}`}
                    className="flex flex-col gap-3 rounded-3xl border border-[#14312c]/8 bg-[#14312c]/[0.03] p-5 sm:flex-row sm:items-center sm:justify-between"
                  >
                    <div className="flex items-center gap-4">
                      <div className="flex size-12 items-center justify-center rounded-2xl bg-[#14312c] text-white">
                        <HandCoins className="size-5" />
                      </div>
                      <div className="flex items-center gap-3 text-sm sm:text-base">
                        <span className="font-medium text-[#14312c]">{settlement.from}</span>
                        <ArrowRight className="size-4 text-muted-foreground" />
                        <span className="font-medium text-[#14312c]">{settlement.to}</span>
                      </div>
                    </div>
                    <p className="font-heading text-2xl text-[#14312c]">
                      {formatCurrency(settlement.amount)}
                    </p>
                  </div>
                ))
              )}
            </CardContent>
          </Card>
        </div>
      )}
    </AppShell>
  );
}
